name: CI
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: ghcr.io/packagrio/packagr-dev:master
    env:
      PROJECT_PATH: /go/src/github.com/packagrio/taggr
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
        run: |
          mkdir -p $PROJECT_PATH
          cp -a $GITHUB_WORKSPACE/* $PROJECT_PATH/
          cd $PROJECT_PATH

          go mod vendor
          mkdir -p vendor/gopkg.in/libgit2/git2go.v25/vendor/libgit2/build/

          # build linux binary
          cp /usr/local/linux/lib/pkgconfig/libgit2.pc vendor/gopkg.in/libgit2/git2go.v25/vendor/libgit2/build/libgit2.pc
          go test -mod vendor -v -tags "static" ./...
          . /scripts/toolchains/linux/linux-build-env.sh && go build -mod vendor -ldflags "-X main.goos=linux -X main.goarch=amd64" -o packagr-taggr-linux-amd64 -tags "static" cmd/taggr/taggr.go

          # build mac binary
          cp /usr/local/osx-ndk-x86/macports/pkgs/opt/local/lib/pkgconfig/libgit2.pc vendor/gopkg.in/libgit2/git2go.v25/vendor/libgit2/build/libgit2.pc
          . /scripts/toolchains/osx/osx-build-env.sh &&  go build -mod vendor -ldflags "-X main.goos=darwin -X main.goarch=amd64" -o packagr-taggr-darwin-amd64 -tags "static" cmd/taggr/taggr.go

          chmod +x packagr-taggr-linux-amd64
          chmod +x packagr-taggr-darwin-amd64
          ./packagr-taggr-linux-amd64 --help
          echo "listing linked libraries" && ldd packagr-taggr-linux-amd64

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: taggr-linux-binary
          path: ${{ env.PROJECT_PATH }}/packagr-taggr-linux-amd64
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: taggr-mac-binary
          path: ${{ env.PROJECT_PATH }}/packagr-taggr-darwin-amd64